### ISSUE TITLE
Loading all images in a wide container

### ISSUE THREAD

**Issue by cjroebuck** [jonathanobino/react-lazy#1]
Hey, not sure what i'm doing wrong but when I have a wide, overflow-x container with loads of images, they all load at the same time rather than when they are scrolled into view.

I'm just using LazyImage component at the moment for my images. Any other config I need to set?

**Comment by jonathanobino** [comment]
Can you provide a codepen/plunker/jsfiddle/jsbin example?

**Comment by jonathanobino** [comment]
Update the package to the 2.0.0 version, it should have fixed the issue (pay attention that this version  is based on requestAnimationFrame)

**Comment by cjroebuck** [comment]
Hi Jon, sorry I never left any code sample/demo. I just upgraded to the new package and it seems to have fixed the issue now. Thanks!
