### ISSUE TITLE
Previous image getting removed when not in view in carousels

### ISSUE THREAD

**Issue by sriksm19** [jonathanobino/react-lazy#2]
Using Swiper carousel, works fine while scrolling forward, but some of the previous images are getting removed when scrolling back, although, upon going back and forth in the carousel, the image appears again. Does it destroy those images/components that are not in view?

**Comment by jonathanobino** [comment]
It should not destroy the image/component once is loaded, can you provide a codepen or similar to show the issue?

**Comment by sriksm19** [comment]
here: http://jsbin.com/xumepihete/edit?html,js,console,output

**Comment by jonathanobino** [comment]
Analyzing the DOM it seems that the slider is adding and removing elements dynamically, maybe changing the slider with a more react-friendly one will fix this issue

**Comment by sriksm19** [comment]
ok will try. thanks
