### ISSUE TITLE
how to add placeholder?

### ISSUE THREAD

**Issue by JackZhang1988** [jonathanobino/react-lazy#3]
how to add a placeholder to display while the image is not visible or loaded?

**Comment by ttmthanh** [comment]
I want to know how to add a placeholder, please help me

**Comment by jonathanobino** [comment]
It's not possible at the moment, but you can send a pull request with the feature

**Comment by ttmthanh** [comment]
Just change this, can you help me? :'( link="" into link="url..."
![ảnh](https://user-images.githubusercontent.com/22828586/146213209-8eaf092d-d3d1-4505-8870-e5b511d73470.png)
